version: "3.8"
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/raspberrypi4-homeassistant:2024.8.3
    volumes:
      - /home/pi/home-assistant/config:/config
      - /home/pi/home-assistant/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  media-server:
    container_name: media-server
    image: nginx:1.21.3
    volumes:
      - /home/pi/home-assistant/media:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    restart: unless-stopped
  proxy-manager:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: proxy-manager
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    volumes:
      - proxy-manager:/data
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  daddns:
    container_name: daddns
    build: docker/daddns
    restart: unless-stopped
    env_file: "./docker/daddns/.env"
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/pi/my-home/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
  node-red:
    build: docker/node-red
    container_name: node-red
    environment:
      - TZ=Europe/Brussels
      - GOOGLE_CLOUD_PROJECT=home-assistant-294520
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - node-red:/data
  esphome:
    image: esphome/esphome:2024.4.0
    container_name: esphome
    volumes:
      - /home/pi/my-home/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped
  unifi:
    image: ghcr.io/jacobalberty/unifi-docker:v7.4.162
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /home/pi/unifi:/unifi
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
    user: unifi
    restart: unless-stopped

volumes:
  proxy-manager:
  letsencrypt:
  node-red:
