FROM nodered/node-red:1.3.6

RUN npm install node-red-contrib-actionflows \
  node-red-contrib-home-assistant-websocket \
  node-red-contrib-stoptimer \
  node-red-contrib-time-range-switch \
  node-red-contrib-timecheck \
  node-red-node-timeswitch \
  node-red-node-base64 \
  node-red-node-suncalc